Portfolio: JavaScript Modal
shyusu4/Portfolio pull request #21
Opened 2022-07-21 13:58 UTC by shyusu4

**Created modal element with JavaScript**

- > Used basic JavaScript syntax.
- > Used JavaScript to manipulate DOM elements.
- > Used JavaScript events.
- > Used objects to store and access data.

2022-07-21 14:04 UTC, shyusu4 commented
I accidentally merged the first pull request that I had for this project: https://github.com/shyusu4/Portfolio/pull/16
I then made another PR and submitted it for re-review, but I was told it was invalid and that I have to revert the changes. https://github.com/shyusu4/Portfolio/pull/19
I tried to revert the changes but, unfortunately, it didn't work so I reached out to a member of the code reviewer team and he told me to just make a PR again in a new branch.

2022-07-21 16:21 UTC, zhadier requested changes
# Hi @shyusu4 & @GhislainMitahi  👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🌤️ 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

 ## Highlights

✔️ No linter errors
✔️ Github flow was set up correctly
✔️ Professional pull request title and description

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 16:21 UTC, zhadier commented on script.js
> +];
- [ ] Great job on making the entire works section dynamic like the previous reviewer requested. But kindly ensure that the project array has individual objects for every single project instead of it being a single object. This will be a much better implementation because if in the near future, you feel like adding another project to your portfolio, the only thing you'll need to do is to add its object to the array and the project card will be dynamically generated inside HTML due to looping. Using the modalArr instead would be even better since it will save a lot of space 👍🏻

2022-07-22 12:08 UTC, danielufeli approved these changes
Hi @shyusu4,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- No Linter Errors✔️
- Clean Code ✔️
- Professional Repo✔️
- Descriptive Readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 12:26 UTC, merged